### ISSUE TITLE
Doesn't work with Xcode 14.3

### ISSUE THREAD

**Issue by km-steve-ham** [ngageoint/simple-features-proj-ios#3]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * SF Proj iOS Version: 5.1.2
  * SF Proj iOS Source: CocoaPods
  * CocoaPods Version: 1.12.0
  * Xcode Version: 14.3
  * Device or Emulator: Device
  * iOS Version: 16.3.1
  * Other Relevant Libraries:

#### Expected Results:

  * What did you expect to happen?
Run HelloWorld app which includes sf-proj-ios (5.1.2) CocoaPods.

#### Observed Results:

  * What happened instead?
File not found: /Applications/Xcode.app/Contents/ Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/ arc/libarclite_iphoneos.a
  * How often does this occur? 100%.

#### Output:

  * Any logs, errors, or output messages?
File not found: /Applications/Xcode.app/Contents/ Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/ arc/libarclite_iphoneos.a

#### Steps to Reproduce:

  1. Install Xcode 14.3.
  2. Create HelloWorldApp.
  3. Install sf-proj-ios CocoaPods.
  4. Run.
#### Relevant Code:

```objectivec
// Code to reproduce the problem?
```

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?

**Comment by km-steve-ham** [comment]
When I click Pods -> TARGETS -> proj4-ios -> Minimum Deployments iOS
iOS version is set to 8.0 by default when I install 'proj-ios' in a HelloWorld app.
After changing it to 11.0 or 12.0 manually the app runs fine. Can you guys change it so that 'proj4-ios' is set to 11.0 by default to support Xcode 14.3? Thanks.

**Comment by km-steve-ham** [comment]
It has been couple weeks, will you be able to change 'proj4-ios' to be set as 11.0 instead of 8.0 please? Thanks.

**Comment by km-steve-ham** [comment]
@bosborn It has been a month. Would you guys be able to change 'proj4-ios' minimum deployments target to 11.0 instead of 8.0 because Xcode 13.0 (Latest version) doesn't support minimum deployment target below 11.0.

When I install proj4-ios on app, I can just change min deployment from settings so it's fine. But for creating CocoaPods library, I cannot do that so it's a problem.

**Comment by bosborn** [comment]
Released a proj4-ios 4.9.3.1 version with [ios 11.0 platform declared in the podspec](https://github.com/CocoaPods/Specs/blob/7b32ac7ca61cb81e40deaa1125aa5b09992864ef/Specs/3/5/2/proj4-ios/4.9.3.1/proj4-ios.podspec.json#L20).

Used by new release [proj-ios 1.0.5](https://github.com/ngageoint/projections-ios/releases/tag/1.0.5) and [sf-proj-ios 5.1.3](https://github.com/ngageoint/simple-features-proj-ios/releases/tag/5.1.3).

**Comment by km-steve-ham** [comment]
Thanks much!
